{{- if .Values.replication.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "mysql.slave.fullname" . }}
  labels: {{- include "mysql.labels" . | nindent 4 }}
    component: slave
spec:
  selector:
    matchLabels: {{- include "mysql.matchLabels" . | nindent 6 }}
      component: slave
  serviceName: "{{ template "mysql.slave.fullname" . }}"
  replicas: {{ .Values.slave.replicas }}
  updateStrategy:
    type: {{ .Values.slave.updateStrategy.type }}
    {{- if (eq "Recreate" .Values.slave.updateStrategy.type) }}
    rollingUpdate: null
    {{- end }}
  template:
    metadata:
      labels: {{- include "mysql.labels" . | nindent 8 }}
        component: slave
      {{- if .Values.slave.annotations }}
      annotations: {{ include "mysql.tplValue" ( dict "value" .Values.slave.annotations "context" $) | nindent 8 }}
      {{- end }}
    spec:
{{- include "mysql.imagePullSecrets" . | indent 6 }}
      {{- if .Values.slave.affinity }}
      affinity: {{- include "mariadb-galera.tplValue" (dict "value" .Values.slave.affinity "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.slave.nodeSelector }}
      nodeSelector: {{- include "mariadb-galera.tplValue" (dict "value" .Values.slave.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.slave.tolerations }}
      tolerations: {{- include "mariadb-galera.tplValue" (dict "value" .Values.slave.tolerations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.slave.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.slave.securityContext.fsGroup }}
        runAsUser: {{ .Values.slave.securityContext.runAsUser }}
      {{- end }}
      {{- if and .Values.volumePermissions.enabled .Values.slave.persistence.enabled }}
      initContainers:
        - name: volume-permissions
          image: {{ template "mysql.volumePermissions.image" . }}
          imagePullPolicy: {{ .Values.volumePermissions.image.pullPolicy | quote }}
          command:
            - /bin/bash
            - -ec
            - |
              chown -R {{ .Values.slave.securityContext.runAsUser }}:{{ .Values.slave.securityContext.fsGroup }} {{ .Values.slave.persistence.mountPath }}
          securityContext:
            runAsUser: 0
          {{- if .Values.volumePermissions.resources }}
          resources: {{- toYaml .Values.volumePermissions.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: {{ .Values.slave.persistence.mountPath }}
      {{- end }}
      containers:
        - name: mysql
          image: {{ template "mysql.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          env:
            - name: MYSQL_REPLICATION_MODE
              value: "slave"
            - name: MYSQL_MASTER_HOST
              value: {{ template "mysql.fullname" . }}
            - name: MYSQL_MASTER_PORT_NUMBER
              value: "3306"
            - name: MYSQL_MASTER_ROOT_USER
              value: "root"
            - name: MYSQL_MASTER_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "mysql.fullname" . }}
                  key: mysql-root-password
            - name: MYSQL_REPLICATION_USER
              value: "{{ .Values.replication.user }}"
            - name: MYSQL_REPLICATION_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "mysql.fullname" . }}
                  key: mysql-replication-password
          ports:
            - name: mysql
              containerPort: 3306
          {{- if .Values.slave.livenessProbe.enabled }}
          livenessProbe:
            exec:
              command: ["sh", "-c", "exec mysqladmin status -uroot -p$MYSQL_MASTER_ROOT_PASSWORD"]
            initialDelaySeconds: {{ .Values.slave.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.slave.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.slave.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.slave.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.slave.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.slave.readinessProbe.enabled }}
          readinessProbe:
            exec:
              command: ["sh", "-c", "exec mysqladmin status -uroot -p$MYSQL_MASTER_ROOT_PASSWORD"]
            initialDelaySeconds: {{ .Values.slave.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.slave.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.slave.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.slave.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.slave.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.master.resources }}
          resources: {{- toYaml .Values.slave.resources | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.slave.persistence.existingClaim }}
            - name: {{ .Values.slave.persistence.existingClaim }}
            {{- else }}
            - name: data
            {{- end }}
              mountPath: {{ .Values.slave.persistence.mountPath }}
            {{- if .Values.slave.config }}
            - name: config
              mountPath: /opt/bitnami/mysql/conf/my.cnf
              subPath: my.cnf
            {{- end }}
        {{- if .Values.metrics.enabled }}
        - name: metrics
          image: {{ template "mysql.metrics.image" . }}
          imagePullPolicy: {{ .Values.metrics.image.pullPolicy | quote }}
          env:
            - name: MYSQL_MASTER_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "mysql.fullname" . }}
                  key: mysql-root-password
          command:
            - /bin/sh
            - -c
            - |
              DATA_SOURCE_NAME="root:$MYSQL_MASTER_ROOT_PASSWORD@(localhost:3306)/" /bin/mysqld_exporter
          ports:
            - name: metrics
              containerPort: 9104
          livenessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
            initialDelaySeconds: 5
            timeoutSeconds: 1
          {{- if .Values.metrics.resources }}
          resources: {{- toYaml .Values.metrics.resources | nindent 12 }}
          {{- end }}
        {{- end }}
      volumes:
        {{- if .Values.slave.config }}
        - name: config
          configMap:
            name: {{ template "mysql.slave.fullname" . }}
        {{- end }}
{{- if not .Values.slave.persistence.enabled }}
        - name: "data"
          emptyDir: {}
{{- else if and .Values.slave.persistence.enabled .Values.slave.persistence.existingClaim }}
        - name: {{ .Values.slave.persistence.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.slave.persistence.existingClaim }}
{{- else if and .Values.slave.persistence.enabled (not .Values.slave.persistence.existingClaim) }}
  volumeClaimTemplates:
    - metadata:
        name: data
        labels: {{- include "mysql.matchLabels" . | nindent 10 }}
          component: slave
      spec:
        accessModes:
        {{- range .Values.slave.persistence.accessModes }}
          - {{ . | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.slave.persistence.size | quote }}
        {{ include "mysql.slave.storageClass" . }}
{{- end }}
{{- end }}
